# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Универ\Программная инженерия\Интерфейс\moreorderinfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiMoreOrderInfo(object):
    def setupUi(self, more_order_info):
        more_order_info.setObjectName("more_order_info")
        more_order_info.resize(401, 346)
        more_order_info.setMinimumSize(QtCore.QSize(401, 346))
        more_order_info.setMaximumSize(QtCore.QSize(401, 346))
        more_order_info.setStyleSheet("background-color: rgb(0, 51, 102);")
        self.order_info_table = QtWidgets.QTableWidget(more_order_info)
        self.order_info_table.setGeometry(QtCore.QRect(60, 60, 280, 212))
        self.order_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.order_info_table.setColumnCount(1)
        self.order_info_table.setObjectName("order_info_table")
        self.order_info_table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(6, 0, item)
        self.order_info_table.horizontalHeader().setVisible(False)
        self.order_info_table.horizontalHeader().setDefaultSectionSize(172)
        self.close_button = QtWidgets.QPushButton(more_order_info)
        self.close_button.setEnabled(True)
        self.close_button.setGeometry(QtCore.QRect(130, 290, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(125,125,125,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.close_button.setObjectName("close_button")
        self.info_about_order_label = QtWidgets.QLabel(more_order_info)
        self.info_about_order_label.setGeometry(QtCore.QRect(0, 20, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_about_order_label.setFont(font)
        self.info_about_order_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.info_about_order_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_about_order_label.setObjectName("info_about_order_label")

        self.retranslateUi(more_order_info)
        QtCore.QMetaObject.connectSlotsByName(more_order_info)

    def retranslateUi(self, more_order_info):
        _translate = QtCore.QCoreApplication.translate
        more_order_info.setWindowTitle(_translate("more_order_info", "Form"))
        item = self.order_info_table.verticalHeaderItem(0)
        item.setText(_translate("more_order_info", "Номер заказа"))
        item = self.order_info_table.verticalHeaderItem(1)
        item.setText(_translate("more_order_info", "Фамилия"))
        item = self.order_info_table.verticalHeaderItem(2)
        item.setText(_translate("more_order_info", "Имя"))
        item = self.order_info_table.verticalHeaderItem(3)
        item.setText(_translate("more_order_info", "Отчество"))
        item = self.order_info_table.verticalHeaderItem(4)
        item.setText(_translate("more_order_info", "Телефон"))
        item = self.order_info_table.verticalHeaderItem(5)
        item.setText(_translate("more_order_info", "E-mail"))
        item = self.order_info_table.verticalHeaderItem(6)
        item.setText(_translate("more_order_info", "Материал"))
        __sortingEnabled = self.order_info_table.isSortingEnabled()
        self.order_info_table.setSortingEnabled(False)
        self.order_info_table.setSortingEnabled(__sortingEnabled)
        self.close_button.setText(_translate("more_order_info", "Закрыть"))
        self.info_about_order_label.setText(_translate("more_order_info", "Информация о заказе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    more_order_info = QtWidgets.QWidget()
    ui = UiMoreOrderInfo()
    ui.setupUi(more_order_info)
    more_order_info.show()
    sys.exit(app.exec_())

