# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Hunte\Downloads\add_supply.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiAddSupply(object):
    def setupUi(self, AddSupply):
        AddSupply.setObjectName("AddSupply")
        AddSupply.resize(484, 450)
        AddSupply.setStyleSheet("background-color: rgb(0, 51, 102);")
        self.type_combobox = QtWidgets.QComboBox(AddSupply)
        self.type_combobox.setGeometry(QtCore.QRect(260, 80, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type_combobox.setFont(font)
        self.type_combobox.setStyleSheet("background:rgb(255, 255, 255)")
        self.type_combobox.setObjectName("type_combobox")
        self.type_material_label = QtWidgets.QLabel(AddSupply)
        self.type_material_label.setGeometry(QtCore.QRect(100, 82, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.type_material_label.setFont(font)
        self.type_material_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.type_material_label.setObjectName("type_material_label")
        self.add_supply_label = QtWidgets.QLabel(AddSupply)
        self.add_supply_label.setGeometry(QtCore.QRect(140, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.add_supply_label.setFont(font)
        self.add_supply_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.add_supply_label.setObjectName("add_supply_label")
        self.contract_lineedit = QtWidgets.QLineEdit(AddSupply)
        self.contract_lineedit.setGeometry(QtCore.QRect(260, 230, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.contract_lineedit.setFont(font)
        self.contract_lineedit.setStyleSheet("background:rgb(255, 255, 255)")
        self.contract_lineedit.setObjectName("contract_lineedit")
        self.contract_number_label = QtWidgets.QLabel(AddSupply)
        self.contract_number_label.setGeometry(QtCore.QRect(88, 234, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.contract_number_label.setFont(font)
        self.contract_number_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.contract_number_label.setObjectName("contract_number_label")
        self.amount_material_label = QtWidgets.QLabel(AddSupply)
        self.amount_material_label.setGeometry(QtCore.QRect(34, 282, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.amount_material_label.setFont(font)
        self.amount_material_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.amount_material_label.setObjectName("amount_material_label")
        self.numer_lineedit = QtWidgets.QLineEdit(AddSupply)
        self.numer_lineedit.setGeometry(QtCore.QRect(260, 280, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numer_lineedit.setFont(font)
        self.numer_lineedit.setStyleSheet("background:rgb(255, 255, 255)")
        self.numer_lineedit.setObjectName("numer_lineedit")
        self.choose_file_button = QtWidgets.QPushButton(AddSupply)
        self.choose_file_button.setEnabled(True)
        self.choose_file_button.setGeometry(QtCore.QRect(100, 330, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.choose_file_button.setFont(font)
        self.choose_file_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.choose_file_button.setObjectName("choose_file_button")
        self.add_button = QtWidgets.QPushButton(AddSupply)
        self.add_button.setEnabled(True)
        self.add_button.setGeometry(QtCore.QRect(110, 385, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.add_button.setObjectName("add_button")
        self.cancel_button = QtWidgets.QPushButton(AddSupply)
        self.cancel_button.setEnabled(True)
        self.cancel_button.setGeometry(QtCore.QRect(250, 385, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.cancel_button.setObjectName("cancel_button")
        self.no_choose_file_lable = QtWidgets.QLabel(AddSupply)
        self.no_choose_file_lable.setGeometry(QtCore.QRect(260, 340, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.no_choose_file_lable.setFont(font)
        self.no_choose_file_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.no_choose_file_lable.setObjectName("no_choose_file_lable")
        self.color_material_label = QtWidgets.QLabel(AddSupply)
        self.color_material_label.setGeometry(QtCore.QRect(90, 132, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.color_material_label.setFont(font)
        self.color_material_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.color_material_label.setObjectName("color_material_label")
        self.color_combobox = QtWidgets.QComboBox(AddSupply)
        self.color_combobox.setGeometry(QtCore.QRect(260, 130, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.color_combobox.setFont(font)
        self.color_combobox.setStyleSheet("background:rgb(255, 255, 255)")
        self.color_combobox.setObjectName("color_combobox")
        self.diametr_yarn_label = QtWidgets.QLabel(AddSupply)
        self.diametr_yarn_label.setGeometry(QtCore.QRect(108, 184, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.diametr_yarn_label.setFont(font)
        self.diametr_yarn_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.diametr_yarn_label.setObjectName("diametr_yarn_label")
        self.diametr_combobox = QtWidgets.QComboBox(AddSupply)
        self.diametr_combobox.setGeometry(QtCore.QRect(260, 180, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.diametr_combobox.setFont(font)
        self.diametr_combobox.setStyleSheet("background:rgb(255, 255, 255)")
        self.diametr_combobox.setObjectName("diametr_combobox")

        self.retranslateUi(AddSupply)
        QtCore.QMetaObject.connectSlotsByName(AddSupply)

    def retranslateUi(self, AddSupply):
        _translate = QtCore.QCoreApplication.translate
        AddSupply.setWindowTitle(_translate("AddSupply", "Form"))
        self.type_material_label.setText(_translate("AddSupply", "Тип материала"))
        self.add_supply_label.setText(_translate("AddSupply", "Добавить поставку"))
        self.contract_number_label.setText(_translate("AddSupply", "Номер договора"))
        self.amount_material_label.setText(_translate("AddSupply", "Количество материала"))
        self.choose_file_button.setText(_translate("AddSupply", "Выбрать файл"))
        self.add_button.setText(_translate("AddSupply", "Добавить"))
        self.cancel_button.setText(_translate("AddSupply", "Отмена"))
        self.no_choose_file_lable.setText(_translate("AddSupply", "Файл не выбран"))
        self.color_material_label.setText(_translate("AddSupply", "Цвет материала"))
        self.diametr_yarn_label.setText(_translate("AddSupply", "Диаметр нити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSupply = QtWidgets.QWidget()
    ui = UiAddSupply()
    ui.setupUi(AddSupply)
    AddSupply.show()
    sys.exit(app.exec_())

