# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Универ\Программная инженерия\Интерфейс\managerwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UiManagerWindow(object):
    def setupUi(self, manager_window):
        manager_window.setObjectName("manager_window")
        manager_window.resize(1231, 678)
        manager_window.setMinimumSize(QtCore.QSize(1231, 678))
        manager_window.setMaximumSize(QtCore.QSize(1231, 678))
        self.centralwidget = QtWidgets.QWidget(manager_window)
        self.centralwidget.setObjectName("centralwidget")
        self.show_orders_info_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_orders_info_button.setEnabled(True)
        self.show_orders_info_button.setGeometry(QtCore.QRect(380, 50, 341, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.show_orders_info_button.setFont(font)
        self.show_orders_info_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.show_orders_info_button.setObjectName("show_orders_info_button")
        self.manager_label = QtWidgets.QLabel(self.centralwidget)
        self.manager_label.setGeometry(QtCore.QRect(20, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.manager_label.setFont(font)
        self.manager_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.manager_label.setObjectName("manager_label")
        self.create_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_order_button.setEnabled(True)
        self.create_order_button.setGeometry(QtCore.QRect(20, 50, 170, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.create_order_button.setFont(font)
        self.create_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.create_order_button.setObjectName("create_order_button")
        self.refactor_order_button = QtWidgets.QPushButton(self.centralwidget)
        self.refactor_order_button.setEnabled(True)
        self.refactor_order_button.setGeometry(QtCore.QRect(200, 50, 170, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refactor_order_button.setFont(font)
        self.refactor_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.refactor_order_button.setObjectName("refactor_order_button")
        self.manager_create_order_group = QtWidgets.QFrame(self.centralwidget)
        self.manager_create_order_group.setEnabled(True)
        self.manager_create_order_group.setGeometry(QtCore.QRect(191, 119, 851, 531))
        self.manager_create_order_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_create_order_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_create_order_group.setObjectName("manager_create_order_group")
        self.surname_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.surname_label.setGeometry(QtCore.QRect(40, 92, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.surname_label.setObjectName("surname_label")
        self.client_info_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.client_info_label.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.client_info_label.setFont(font)
        self.client_info_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.client_info_label.setObjectName("client_info_label")
        self.name_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.name_label.setGeometry(QtCore.QRect(40, 132, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_label.setObjectName("name_label")
        self.add_order_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.add_order_label.setGeometry(QtCore.QRect(300, 0, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.add_order_label.setFont(font)
        self.add_order_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.add_order_label.setObjectName("add_order_label")
        self.patronymic_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.patronymic_label.setGeometry(QtCore.QRect(40, 172, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.patronymic_label.setFont(font)
        self.patronymic_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.patronymic_label.setObjectName("patronymic_label")
        self.surname_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.surname_text.setGeometry(QtCore.QRect(160, 90, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surname_text.setFont(font)
        self.surname_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.surname_text.setText("")
        self.surname_text.setObjectName("surname_text")
        self.name_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.name_text.setGeometry(QtCore.QRect(160, 130, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_text.setFont(font)
        self.name_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_text.setText("")
        self.name_text.setObjectName("name_text")
        self.patronymic_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.patronymic_text.setEnabled(True)
        self.patronymic_text.setGeometry(QtCore.QRect(160, 170, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patronymic_text.setFont(font)
        self.patronymic_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.patronymic_text.setText("")
        self.patronymic_text.setObjectName("patronymic_text")
        self.phone_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.phone_label.setGeometry(QtCore.QRect(40, 212, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.phone_label.setObjectName("phone_label")
        self.phone_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.phone_text.setEnabled(True)
        self.phone_text.setGeometry(QtCore.QRect(160, 210, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_text.setFont(font)
        self.phone_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone_text.setText("")
        self.phone_text.setObjectName("phone_text")
        self.additional_info_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.additional_info_label.setGeometry(QtCore.QRect(470, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.additional_info_label.setFont(font)
        self.additional_info_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.additional_info_label.setObjectName("additional_info_label")
        self.additional_info_text = QtWidgets.QTextEdit(self.manager_create_order_group)
        self.additional_info_text.setGeometry(QtCore.QRect(490, 90, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.additional_info_text.setFont(font)
        self.additional_info_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.additional_info_text.setObjectName("additional_info_text")
        self.model_info_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.model_info_label.setGeometry(QtCore.QRect(20, 286, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.model_info_label.setFont(font)
        self.model_info_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.model_info_label.setObjectName("model_info_label")
        self.file_with_model_radio = QtWidgets.QRadioButton(self.manager_create_order_group)
        self.file_with_model_radio.setGeometry(QtCore.QRect(40, 326, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_with_model_radio.setFont(font)
        self.file_with_model_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_with_model_radio.setChecked(True)
        self.file_with_model_radio.setObjectName("file_with_model_radio")
        self.sketch_of_model_radio = QtWidgets.QRadioButton(self.manager_create_order_group)
        self.sketch_of_model_radio.setGeometry(QtCore.QRect(230, 326, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sketch_of_model_radio.setFont(font)
        self.sketch_of_model_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sketch_of_model_radio.setObjectName("sketch_of_model_radio")
        self.select_file_button = QtWidgets.QPushButton(self.manager_create_order_group)
        self.select_file_button.setEnabled(True)
        self.select_file_button.setGeometry(QtCore.QRect(230, 352, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.select_file_button.setFont(font)
        self.select_file_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.select_file_button.setObjectName("select_file_button")
        self.selected_file_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.selected_file_label.setGeometry(QtCore.QRect(80, 356, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selected_file_label.setFont(font)
        self.selected_file_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_file_label.setObjectName("selected_file_label")
        self.model_materials_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.model_materials_label.setGeometry(QtCore.QRect(20, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.model_materials_label.setFont(font)
        self.model_materials_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.model_materials_label.setObjectName("model_materials_label")
        self.plastic_color_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.plastic_color_label.setGeometry(QtCore.QRect(40, 482, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.plastic_color_label.setFont(font)
        self.plastic_color_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.plastic_color_label.setObjectName("plastic_color_label")
        self.type_of_plastic_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.type_of_plastic_label.setGeometry(QtCore.QRect(40, 442, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.type_of_plastic_label.setFont(font)
        self.type_of_plastic_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.type_of_plastic_label.setObjectName("type_of_plastic_label")
        self.type_of_plastic_combobox = QtWidgets.QComboBox(self.manager_create_order_group)
        self.type_of_plastic_combobox.setGeometry(QtCore.QRect(200, 440, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.type_of_plastic_combobox.setFont(font)
        self.type_of_plastic_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.type_of_plastic_combobox.setObjectName("type_of_plastic_combobox")
        self.color_of_plastic_combobox = QtWidgets.QComboBox(self.manager_create_order_group)
        self.color_of_plastic_combobox.setGeometry(QtCore.QRect(200, 480, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.color_of_plastic_combobox.setFont(font)
        self.color_of_plastic_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color_of_plastic_combobox.setObjectName("color_of_plastic_combobox")
        self.short_description_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.short_description_label.setGeometry(QtCore.QRect(470, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.short_description_label.setFont(font)
        self.short_description_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.short_description_label.setObjectName("short_description_label")
        self.short_description_text = QtWidgets.QTextEdit(self.manager_create_order_group)
        self.short_description_text.setGeometry(QtCore.QRect(490, 280, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.short_description_text.setFont(font)
        self.short_description_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.short_description_text.setObjectName("short_description_text")
        self.price_info_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.price_info_label.setGeometry(QtCore.QRect(470, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.price_info_label.setFont(font)
        self.price_info_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.price_info_label.setObjectName("price_info_label")
        self.finale_price_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.finale_price_label.setGeometry(QtCore.QRect(490, 440, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.finale_price_label.setFont(font)
        self.finale_price_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.finale_price_label.setObjectName("finale_price_label")
        self.add_order_button = QtWidgets.QPushButton(self.manager_create_order_group)
        self.add_order_button.setEnabled(True)
        self.add_order_button.setGeometry(QtCore.QRect(630, 470, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_order_button.setFont(font)
        self.add_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.add_order_button.setObjectName("add_order_button")
        self.email_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.email_text.setEnabled(True)
        self.email_text.setGeometry(QtCore.QRect(160, 248, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_text.setFont(font)
        self.email_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_text.setText("")
        self.email_text.setObjectName("email_text")
        self.email_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.email_label.setGeometry(QtCore.QRect(40, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_label.setObjectName("email_label")
        self.manager_refactor_order_group = QtWidgets.QFrame(self.centralwidget)
        self.manager_refactor_order_group.setEnabled(True)
        self.manager_refactor_order_group.setGeometry(QtCore.QRect(0, 120, 1231, 531))
        self.manager_refactor_order_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_refactor_order_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_refactor_order_group.setObjectName("manager_refactor_order_group")
        self.manager_refactor_order_group.hide()
        self.surname_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.surname_label_ref.setGeometry(QtCore.QRect(420, 92, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.surname_label_ref.setFont(font)
        self.surname_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.surname_label_ref.setObjectName("surname_label_ref")
        self.client_info_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.client_info_label_ref.setGeometry(QtCore.QRect(400, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.client_info_label_ref.setFont(font)
        self.client_info_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.client_info_label_ref.setObjectName("client_info_label_ref")
        self.name_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.name_label_ref.setGeometry(QtCore.QRect(420, 130, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_label_ref.setFont(font)
        self.name_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_label_ref.setObjectName("name_label_ref")
        self.refactor_order_label = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.refactor_order_label.setGeometry(QtCore.QRect(460, 0, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.refactor_order_label.setFont(font)
        self.refactor_order_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.refactor_order_label.setObjectName("refactor_order_label")
        self.patronymic_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.patronymic_label_ref.setGeometry(QtCore.QRect(420, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.patronymic_label_ref.setFont(font)
        self.patronymic_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.patronymic_label_ref.setObjectName("patronymic_label_ref")
        self.surname_text_ref = QtWidgets.QLineEdit(self.manager_refactor_order_group)
        self.surname_text_ref.setGeometry(QtCore.QRect(540, 90, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surname_text_ref.setFont(font)
        self.surname_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.surname_text_ref.setText("")
        self.surname_text_ref.setObjectName("surname_text_ref")
        self.name_text_ref = QtWidgets.QLineEdit(self.manager_refactor_order_group)
        self.name_text_ref.setGeometry(QtCore.QRect(540, 128, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_text_ref.setFont(font)
        self.name_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_text_ref.setText("")
        self.name_text_ref.setObjectName("name_text_ref")
        self.patronymic_text_ref = QtWidgets.QLineEdit(self.manager_refactor_order_group)
        self.patronymic_text_ref.setEnabled(True)
        self.patronymic_text_ref.setGeometry(QtCore.QRect(540, 168, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patronymic_text_ref.setFont(font)
        self.patronymic_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.patronymic_text_ref.setText("")
        self.patronymic_text_ref.setObjectName("patronymic_text_ref")
        self.phone_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.phone_label_ref.setGeometry(QtCore.QRect(420, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.phone_label_ref.setFont(font)
        self.phone_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.phone_label_ref.setObjectName("phone_label_ref")
        self.phone_text_ref = QtWidgets.QLineEdit(self.manager_refactor_order_group)
        self.phone_text_ref.setEnabled(True)
        self.phone_text_ref.setGeometry(QtCore.QRect(540, 208, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_text_ref.setFont(font)
        self.phone_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone_text_ref.setText("")
        self.phone_text_ref.setObjectName("phone_text_ref")
        self.additional_info_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.additional_info_label_ref.setGeometry(QtCore.QRect(850, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.additional_info_label_ref.setFont(font)
        self.additional_info_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.additional_info_label_ref.setObjectName("additional_info_label_ref")
        self.additional_info_text_ref = QtWidgets.QTextEdit(self.manager_refactor_order_group)
        self.additional_info_text_ref.setGeometry(QtCore.QRect(870, 90, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.additional_info_text_ref.setFont(font)
        self.additional_info_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.additional_info_text_ref.setObjectName("additional_info_text_ref")
        self.model_info_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.model_info_label_ref.setGeometry(QtCore.QRect(400, 286, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.model_info_label_ref.setFont(font)
        self.model_info_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.model_info_label_ref.setObjectName("model_info_label_ref")
        self.file_with_model_radio_ref = QtWidgets.QRadioButton(self.manager_refactor_order_group)
        self.file_with_model_radio_ref.setGeometry(QtCore.QRect(420, 326, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_with_model_radio_ref.setFont(font)
        self.file_with_model_radio_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_with_model_radio_ref.setChecked(True)
        self.file_with_model_radio_ref.setObjectName("file_with_model_radio_ref")
        self.sketch_of_model_radio_ref = QtWidgets.QRadioButton(self.manager_refactor_order_group)
        self.sketch_of_model_radio_ref.setGeometry(QtCore.QRect(610, 326, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sketch_of_model_radio_ref.setFont(font)
        self.sketch_of_model_radio_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.sketch_of_model_radio_ref.setObjectName("sketch_of_model_radio_ref")
        self.select_file_button_ref = QtWidgets.QPushButton(self.manager_refactor_order_group)
        self.select_file_button_ref.setEnabled(True)
        self.select_file_button_ref.setGeometry(QtCore.QRect(610, 352, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.select_file_button_ref.setFont(font)
        self.select_file_button_ref.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.select_file_button_ref.setObjectName("select_file_button_ref")
        self.selected_file_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.selected_file_label_ref.setGeometry(QtCore.QRect(460, 356, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selected_file_label_ref.setFont(font)
        self.selected_file_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_file_label_ref.setObjectName("selected_fil_label_ref")
        self.model_materials_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.model_materials_label_ref.setGeometry(QtCore.QRect(400, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.model_materials_label_ref.setFont(font)
        self.model_materials_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.model_materials_label_ref.setObjectName("model_materials_label_ref")
        self.plastic_color_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.plastic_color_label_ref.setGeometry(QtCore.QRect(420, 482, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.plastic_color_label_ref.setFont(font)
        self.plastic_color_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.plastic_color_label_ref.setObjectName("plastic_color_label_ref")
        self.type_of_plastic_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.type_of_plastic_label_ref.setGeometry(QtCore.QRect(420, 442, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.type_of_plastic_label_ref.setFont(font)
        self.type_of_plastic_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.type_of_plastic_label_ref.setObjectName("type_of_plastic_label_ref")
        self.type_of_plastic_combobox_ref = QtWidgets.QComboBox(self.manager_refactor_order_group)
        self.type_of_plastic_combobox_ref.setGeometry(QtCore.QRect(580, 440, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.type_of_plastic_combobox_ref.setFont(font)
        self.type_of_plastic_combobox_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.type_of_plastic_combobox_ref.setObjectName("type_of_plastic_combobox_ref")
        self.color_of_plastic_combobox_ref = QtWidgets.QComboBox(self.manager_refactor_order_group)
        self.color_of_plastic_combobox_ref.setGeometry(QtCore.QRect(580, 480, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.color_of_plastic_combobox_ref.setFont(font)
        self.color_of_plastic_combobox_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color_of_plastic_combobox_ref.setObjectName("color_of_plastic_combobox_ref")
        self.short_description_label_re = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.short_description_label_re.setGeometry(QtCore.QRect(850, 240, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.short_description_label_re.setFont(font)
        self.short_description_label_re.setStyleSheet("color: rgb(255, 255, 255);")
        self.short_description_label_re.setObjectName("short_description_label_re")
        self.short_description_text_ref = QtWidgets.QTextEdit(self.manager_refactor_order_group)
        self.short_description_text_ref.setGeometry(QtCore.QRect(870, 280, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.short_description_text_ref.setFont(font)
        self.short_description_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.short_description_text_ref.setObjectName("short_description_text_ref")
        self.price_info_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.price_info_label_ref.setGeometry(QtCore.QRect(850, 400, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.price_info_label_ref.setFont(font)
        self.price_info_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.price_info_label_ref.setObjectName("price_info_label_ref")
        self.finale_price_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.finale_price_label_ref.setGeometry(QtCore.QRect(870, 440, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.finale_price_label_ref.setFont(font)
        self.finale_price_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.finale_price_label_ref.setObjectName("finale_price_label_ref")
        self.refactor_order_button_ref = QtWidgets.QPushButton(self.manager_refactor_order_group)
        self.refactor_order_button_ref.setEnabled(True)
        self.refactor_order_button_ref.setGeometry(QtCore.QRect(980, 470, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refactor_order_button_ref.setFont(font)
        self.refactor_order_button_ref.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.refactor_order_button_ref.setObjectName("refactor_order_button_ref")
        self.need_refactoring_order_combobox = QtWidgets.QComboBox(self.manager_refactor_order_group)
        self.need_refactoring_order_combobox.setGeometry(QtCore.QRect(40, 100, 301, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.need_refactoring_order_combobox.setFont(font)
        self.need_refactoring_order_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.need_refactoring_order_combobox.setObjectName("need_refactoring_order_combobox")
        self.need_refactoring_order_label = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.need_refactoring_order_label.setGeometry(QtCore.QRect(20, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.need_refactoring_order_label.setFont(font)
        self.need_refactoring_order_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.need_refactoring_order_label.setObjectName("need_refactoring_order_label")
        self.node_of_refactoring_label = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.node_of_refactoring_label.setGeometry(QtCore.QRect(20, 150, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.node_of_refactoring_label.setFont(font)
        self.node_of_refactoring_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.node_of_refactoring_label.setObjectName("node_of_refactoring_label")
        self.note_of_refactoring_text = QtWidgets.QTextEdit(self.manager_refactor_order_group)
        self.note_of_refactoring_text.setGeometry(QtCore.QRect(40, 190, 301, 311))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.note_of_refactoring_text.setFont(font)
        self.note_of_refactoring_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.note_of_refactoring_text.setObjectName("note_of_refactoring")
        self.email_text_ref = QtWidgets.QLineEdit(self.manager_refactor_order_group)
        self.email_text_ref.setEnabled(True)
        self.email_text_ref.setGeometry(QtCore.QRect(540, 248, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_text_ref.setFont(font)
        self.email_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_text_ref.setText("")
        self.email_text_ref.setObjectName("email_text_ref")
        self.email_label_ref = QtWidgets.QLabel(self.manager_refactor_order_group)
        self.email_label_ref.setGeometry(QtCore.QRect(420, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.email_label_ref.setFont(font)
        self.email_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_label_ref.setObjectName("email_label_ref")
        self.manager_show_orders_info_group = QtWidgets.QFrame(self.centralwidget)
        self.manager_show_orders_info_group.setGeometry(QtCore.QRect(95, 120, 1041, 531))
        self.manager_show_orders_info_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_show_orders_info_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_show_orders_info_group.setObjectName("manager_show_orders_info_group")
        self.manager_show_orders_info_group.hide()
        self.orders_info_table = QtWidgets.QTableWidget(self.manager_show_orders_info_group)
        self.orders_info_table.setGeometry(QtCore.QRect(0, 60, 1041, 391))
        self.orders_info_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.orders_info_table.setFont(font)
        self.orders_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.orders_info_table.setDragEnabled(False)
        self.orders_info_table.setAlternatingRowColors(False)
        self.orders_info_table.setShowGrid(True)
        self.orders_info_table.setColumnCount(4)
        self.orders_info_table.setObjectName("orders_info_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(0, item)
        self.orders_info_table.setColumnWidth(0, 140)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(1, item)
        self.orders_info_table.setColumnWidth(1, 140)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(2, item)
        self.orders_info_table.setColumnWidth(2, 540)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(3, item)
        self.orders_info_table.setColumnWidth(3, 219)
        item = QtWidgets.QTableWidgetItem()
        self.orders_info_table.setItem(0, 0, item)
        self.orders_info_table.verticalHeader().setVisible(False)
        self.orders_info_label = QtWidgets.QLabel(self.manager_show_orders_info_group)
        self.orders_info_label.setGeometry(QtCore.QRect(360, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.orders_info_label.setFont(font)
        self.orders_info_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.orders_info_label.setObjectName("orders_info_label")
        self.show_more_info_button = QtWidgets.QPushButton(self.manager_show_orders_info_group)
        self.show_more_info_button.setEnabled(True)
        self.show_more_info_button.setGeometry(QtCore.QRect(260, 460, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.show_more_info_button.setFont(font)
        self.show_more_info_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
        "border-color: rgb(102, 102, 102);\n"
        "border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.show_more_info_button.setObjectName("show_more_info_button")
        self.delete_order_button = QtWidgets.QPushButton(self.manager_show_orders_info_group)
        self.delete_order_button.setEnabled(True)
        self.delete_order_button.setGeometry(QtCore.QRect(560, 460, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete_order_button.setFont(font)
        self.delete_order_button.setStyleSheet(
                "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
                "border-color: rgb(102, 102, 102);\n"
                "border: 2px solid rgb(102, 102, 102);\n"
                "border-radius: 6px;\n"
                "")
        self.delete_order_button.setObjectName("delete_order_button")
        self.orders_info_label.raise_()
        self.orders_info_table.raise_()
        self.show_more_info_button.raise_()
        self.manager_create_order_group.raise_()
        self.manager_refactor_order_group.raise_()
        self.manager_show_orders_info_group.raise_()
        self.show_orders_info_button.raise_()
        self.manager_label.raise_()
        self.create_order_button.raise_()
        self.refactor_order_button.raise_()
        manager_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(manager_window)
        self.statusbar.setObjectName("statusbar")
        manager_window.setStatusBar(self.statusbar)

        self.retranslateUi(manager_window)
        QtCore.QMetaObject.connectSlotsByName(manager_window)

    def retranslateUi(self, manager_window):
        _translate = QtCore.QCoreApplication.translate
        manager_window.setWindowTitle(_translate("manager_window", "Manager Window"))
        self.show_orders_info_button.setText(_translate("manager_window", "Просмотреть информацию о заказах"))
        self.manager_label.setText(_translate("manager_window", "Менджер по работе с клиентами"))
        self.create_order_button.setText(_translate("manager_window", "Офромить заказ"))
        self.refactor_order_button.setText(_translate("manager_window", "Доработать заказ"))
        self.surname_label.setText(_translate("manager_window", "Фамилия"))
        self.client_info_label.setText(_translate("manager_window", "Информация о клиенте"))
        self.name_label.setText(_translate("manager_window", "Имя"))
        self.add_order_label.setText(_translate("manager_window", "ОФОРМЛЕНИЕ ЗАКАЗА"))
        self.patronymic_label.setText(_translate("manager_window", "Отчество"))
        self.phone_label.setText(_translate("manager_window", "Телефон"))
        self.additional_info_label.setText(_translate("manager_window", "Дополнительная информация"))
        self.model_info_label.setText(_translate("manager_window", "Информация о моделе"))
        self.file_with_model_radio.setText(_translate("manager_window", "Файл с моделью"))
        self.sketch_of_model_radio.setText(_translate("manager_window", "Эскиз модели"))
        self.select_file_button.setText(_translate("manager_window", "Выбрать файл"))
        self.selected_file_label.setText(_translate("manager_window", "Файл не выбран"))
        self.model_materials_label.setText(_translate("manager_window", "Материалы модели"))
        self.plastic_color_label.setText(_translate("manager_window", "Цвет пластика"))
        self.type_of_plastic_label.setText(_translate("manager_window", "Тип пластика"))
        self.short_description_label.setText(_translate("manager_window", "Краткое описание"))
        self.price_info_label.setText(_translate("manager_window", "Итоговая сумма"))
        self.finale_price_label.setText(_translate("manager_window", "0 рублей"))
        self.add_order_button.setText(_translate("manager_window", "Добавить заказ"))
        self.email_label.setText(_translate("manager_window", "E-mail"))
        self.surname_label_ref.setText(_translate("manager_window", "Фамилия"))
        self.client_info_label_ref.setText(_translate("manager_window", "Информация о клиенте"))
        self.name_label_ref.setText(_translate("manager_window", "Имя"))
        self.refactor_order_label.setText(_translate("manager_window", "ДОРАБОТАТЬ ЗАКАЗ"))
        self.patronymic_label_ref.setText(_translate("manager_window", "Отчество"))
        self.phone_label_ref.setText(_translate("manager_window", "Телефон"))
        self.additional_info_label_ref.setText(_translate("manager_window", "Дополнительная информация"))
        self.additional_info_text_ref.setHtml(_translate("manager_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.model_info_label_ref.setText(_translate("manager_window", "Информация о моделе"))
        self.file_with_model_radio_ref.setText(_translate("manager_window", "Файл с моделью"))
        self.sketch_of_model_radio_ref.setText(_translate("manager_window", "Эскиз модели"))
        self.select_file_button_ref.setText(_translate("manager_window", "Выбрать файл"))
        self.selected_file_label_ref.setText(_translate("manager_window", "Файл не выбран"))
        self.model_materials_label_ref.setText(_translate("manager_window", "Материалы модели"))
        self.plastic_color_label_ref.setText(_translate("manager_window", "Цвет пластика"))
        self.type_of_plastic_label_ref.setText(_translate("manager_window", "Тип пластика"))
        self.short_description_label_re.setText(_translate("manager_window", "Краткое описание"))
        self.short_description_text_ref.setHtml(_translate("manager_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.price_info_label_ref.setText(_translate("manager_window", "Итоговая сумма"))
        self.finale_price_label_ref.setText(_translate("manager_window", "0 рублей"))
        self.refactor_order_button_ref.setText(_translate("manager_window", "Обновить информацию"))
        self.need_refactoring_order_label.setText(_translate("manager_window", "Требующие доработки заказы"))
        self.node_of_refactoring_label.setText(_translate("manager_window", "Заметка об исправлении"))
        self.email_label_ref.setText(_translate("manager_window", "E-mail"))
        item = self.orders_info_table.horizontalHeaderItem(0)
        item.setText(_translate("manager_window", "Номер заказа"))
        item = self.orders_info_table.horizontalHeaderItem(1)
        item.setText(_translate("manager_window", "Дата оформления"))
        item = self.orders_info_table.horizontalHeaderItem(2)
        item.setText(_translate("manager_window", "Описание"))
        item = self.orders_info_table.horizontalHeaderItem(3)
        item.setText(_translate("manager_window", "Статус"))
        __sortingEnabled = self.orders_info_table.isSortingEnabled()
        self.orders_info_table.setSortingEnabled(False)
        self.orders_info_table.setSortingEnabled(__sortingEnabled)
        self.orders_info_label.setText(_translate("manager_window", "ИНФОРМАЦИЯ О ЗАКАЗАХ"))
        self.show_more_info_button.setText(_translate("manager_window", "Подробная информация"))
        self.delete_order_button.setText(_translate("manager_window", "Отменить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manager_window = QtWidgets.QMainWindow()
    ui = UiManagerWindow()
    ui.setupUi(manager_window)
    print(ui.orders_info_table.rowCount())
    manager_window.show()
    sys.exit(app.exec_())

