# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Универ\Программная инженерия\Интерфейс\snabzenecwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UiSnabzenecWindow(object):
    def setupUi(self, SnabzenecWindow):
        SnabzenecWindow.setObjectName("SnabzenecWindow")
        SnabzenecWindow.resize(800, 680)
        SnabzenecWindow.setMinimumSize(800, 680)
        SnabzenecWindow.setMaximumSize(800, 680)
        SnabzenecWindow.setStyleSheet("background-color: rgb(0, 51, 102);")
        self.centralwidget = QtWidgets.QWidget(SnabzenecWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zakupka_group = QtWidgets.QFrame(self.centralwidget)
        self.zakupka_group.setGeometry(QtCore.QRect(109, 90, 581, 571))
        self.zakupka_group.setMaximumSize(QtCore.QSize(581, 621))
        self.zakupka_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.zakupka_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.zakupka_group.setObjectName("zakupka_group")
        self.zakupka_group.hide()
        self.confirm_delivery_button = QtWidgets.QPushButton(self.zakupka_group)
        self.confirm_delivery_button.setEnabled(True)
        self.confirm_delivery_button.setGeometry(QtCore.QRect(220, 440, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_delivery_button.setFont(font)
        self.confirm_delivery_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.confirm_delivery_button.setObjectName("confirm_delivery_button")
        self.information_delivery_button = QtWidgets.QPushButton(self.zakupka_group)
        self.information_delivery_button.setEnabled(True)
        self.information_delivery_button.setGeometry(QtCore.QRect(170, 500, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.information_delivery_button.setFont(font)
        self.information_delivery_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.information_delivery_button.setObjectName("information_delivery_button")
        self.cancel_supply_button = QtWidgets.QPushButton(self.zakupka_group)
        self.cancel_supply_button.setEnabled(True)
        self.cancel_supply_button.setGeometry(QtCore.QRect(390, 440, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_supply_button.setFont(font)
        self.cancel_supply_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.cancel_supply_button.setObjectName("cancel_supply_button")
        self.supply_info_table = QtWidgets.QTableWidget(self.zakupka_group)
        self.supply_info_table.setGeometry(QtCore.QRect(100, 40, 371, 391))
        self.supply_info_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.supply_info_table.setFont(font)
        self.supply_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.supply_info_table.setDragEnabled(False)
        self.supply_info_table.setAlternatingRowColors(False)
        self.supply_info_table.setShowGrid(True)
        self.supply_info_table.setRowCount(0)
        self.supply_info_table.setColumnCount(2)
        self.supply_info_table.setObjectName("supply_info_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.supply_info_table.setHorizontalHeaderItem(0, item)
        self.supply_info_table.setColumnWidth(0, 169)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.supply_info_table.setHorizontalHeaderItem(1, item)
        self.supply_info_table.setColumnWidth(1, 200)
        self.supply_info_table.horizontalHeader().setVisible(True)
        self.supply_info_table.horizontalHeader().setHighlightSections(True)
        self.supply_info_table.verticalHeader().setVisible(False)
        self.add_supply_button = QtWidgets.QPushButton(self.zakupka_group)
        self.add_supply_button.setEnabled(True)
        self.add_supply_button.setGeometry(QtCore.QRect(80, 440, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_supply_button.setFont(font)
        self.add_supply_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.add_supply_button.setObjectName("add_supply_button")
        self.supply_label = QtWidgets.QLabel(self.zakupka_group)
        self.supply_label.setGeometry(QtCore.QRect(245, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.supply_label.setFont(font)
        self.supply_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.supply_label.setObjectName("supply_label")
        self.manager_label = QtWidgets.QLabel(self.centralwidget)
        self.manager_label.setGeometry(QtCore.QRect(20, 10, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.manager_label.setFont(font)
        self.manager_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.manager_label.setObjectName("manager_label")
        self.stock_button = QtWidgets.QPushButton(self.centralwidget)
        self.stock_button.setEnabled(True)
        self.stock_button.setGeometry(QtCore.QRect(180, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stock_button.setFont(font)
        self.stock_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.stock_button.setObjectName("stock_button")
        self.application_button = QtWidgets.QPushButton(self.centralwidget)
        self.application_button.setEnabled(True)
        self.application_button.setGeometry(QtCore.QRect(350, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.application_button.setFont(font)
        self.application_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.application_button.setObjectName("application_button")
        self.buy_button = QtWidgets.QPushButton(self.centralwidget)
        self.buy_button.setEnabled(True)
        self.buy_button.setGeometry(QtCore.QRect(520, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buy_button.setFont(font)
        self.buy_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.buy_button.setObjectName("buy_button")
        self.sklad_group = QtWidgets.QFrame(self.centralwidget)
        self.sklad_group.setGeometry(QtCore.QRect(-1, 90, 801, 571))
        self.sklad_group.setMaximumSize(QtCore.QSize(801, 621))
        self.sklad_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sklad_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sklad_group.setObjectName("sklad_group")
        self.stock_label = QtWidgets.QLabel(self.sklad_group)
        self.stock_label.setGeometry(QtCore.QRect(360, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stock_label.setFont(font)
        self.stock_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.stock_label.setObjectName("stock_label")
        self.info_table = QtWidgets.QTableWidget(self.sklad_group)
        self.info_table.setGeometry(QtCore.QRect(20, 40, 761, 491))
        self.info_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.info_table.setFont(font)
        self.info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.info_table.setDragEnabled(False)
        self.info_table.setAlternatingRowColors(False)
        self.info_table.setShowGrid(True)
        self.info_table.setRowCount(0)
        self.info_table.setColumnCount(5)
        self.info_table.setObjectName("info_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.info_table.setHorizontalHeaderItem(0, item)
        self.info_table.setColumnWidth(0, 150)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.info_table.setHorizontalHeaderItem(1, item)
        self.info_table.setColumnWidth(1, 150)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.info_table.setHorizontalHeaderItem(2, item)
        self.info_table.setColumnWidth(2, 150)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.info_table.setHorizontalHeaderItem(3, item)
        self.info_table.setColumnWidth(3, 159)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.info_table.setHorizontalHeaderItem(4, item)
        self.info_table.setColumnWidth(4, 150)
        self.stock_label.raise_()
        self.info_table.raise_()
        self.zakupka_group.raise_()
        self.zayavka_frame = QtWidgets.QFrame(self.centralwidget)
        self.zayavka_frame.setGeometry(QtCore.QRect(0, 90, 801, 571))
        self.zayavka_frame.setMaximumSize(QtCore.QSize(801, 621))
        self.zayavka_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.zayavka_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.zayavka_frame.setObjectName("zayavka_frame")
        self.zayavka_frame.hide()
        self.application_label = QtWidgets.QLabel(self.zayavka_frame)
        self.application_label.setGeometry(QtCore.QRect(360, 0, 86, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.application_label.setFont(font)
        self.application_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.application_label.setObjectName("application_label")
        self.application_info_table = QtWidgets.QTableWidget(self.zayavka_frame)
        self.application_info_table.setGeometry(QtCore.QRect(30, 40, 741, 451))
        self.application_info_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.application_info_table.setFont(font)
        self.application_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.application_info_table.setDragEnabled(False)
        self.application_info_table.setAlternatingRowColors(False)
        self.application_info_table.setShowGrid(True)
        self.application_info_table.setRowCount(0)
        self.application_info_table.setColumnCount(6)
        self.application_info_table.setObjectName("application_info_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(0, item)
        self.application_info_table.setColumnWidth(0, 100)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(1, item)
        self.application_info_table.setColumnWidth(1, 100)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(2, item)
        self.application_info_table.setColumnWidth(2, 100)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(3, item)
        self.application_info_table.setColumnWidth(3, 140)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(4, item)
        self.application_info_table.setColumnWidth(4, 130)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.application_info_table.setHorizontalHeaderItem(5, item)
        self.application_info_table.setColumnWidth(5, 169)
        self.send_material_button = QtWidgets.QPushButton(self.zayavka_frame)
        self.send_material_button.setEnabled(True)
        self.send_material_button.setGeometry(QtCore.QRect(230, 500, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_material_button.setFont(font)
        self.send_material_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.send_material_button.setObjectName("send_material_button")
        self.date_button = QtWidgets.QPushButton(self.zayavka_frame)
        self.date_button.setEnabled(True)
        self.date_button.setGeometry(QtCore.QRect(430, 500, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date_button.setFont(font)
        self.date_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
            "border-color: rgb(102, 102, 102);\n"
            "border: 2px solid rgb(102, 102, 102);\n"
            "border-radius: 6px;\n"
            "")
        self.date_button.setObjectName("date_button")
        self.application_label.raise_()
        self.application_info_table.raise_()
        self.send_material_button.raise_()
        self.date_button.raise_()
        self.sklad_group.raise_()
        self.sklad_group.raise_()
        self.zakupka_group.raise_()
        self.zayavka_frame.raise_()
        self.manager_label.raise_()
        self.stock_button.raise_()
        self.application_button.raise_()
        self.buy_button.raise_()
        SnabzenecWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SnabzenecWindow)
        self.statusbar.setObjectName("statusbar")
        SnabzenecWindow.setStatusBar(self.statusbar)

        self.stock_button.clicked.connect(self.show_sklad)
        self.application_button.clicked.connect(self.show_zayavka)
        self.buy_button.clicked.connect(self.show_zakupka)

        self.retranslateUi(SnabzenecWindow)
        QtCore.QMetaObject.connectSlotsByName(SnabzenecWindow)

    def retranslateUi(self, SnabzenecWindow):
        _translate = QtCore.QCoreApplication.translate
        SnabzenecWindow.setWindowTitle(_translate("SnabzenecWindow", "MainWindow"))
        self.confirm_delivery_button.setText(_translate("SnabzenecWindow", "Поддтвердить\n"
            " получение"))
        self.information_delivery_button.setText(_translate("SnabzenecWindow", "Просмотреть информацию\n"
            " о поставке"))
        self.cancel_supply_button.setText(_translate("SnabzenecWindow", "Отменить\n"
            "поставку"))
        item = self.supply_info_table.horizontalHeaderItem(0)
        item.setText(_translate("SnabzenecWindow", "Номер договора"))
        item = self.supply_info_table.horizontalHeaderItem(1)
        item.setText(_translate("SnabzenecWindow", "Статус"))
        self.add_supply_button.setText(_translate("SnabzenecWindow", "Добавить \n"
"поставку"))
        self.supply_label.setText(_translate("SnabzenecWindow", "Закупки"))
        self.manager_label.setText(_translate("SnabzenecWindow", "Менеджер по снабжению"))
        self.stock_button.setText(_translate("SnabzenecWindow", "Склад"))
        self.application_button.setText(_translate("SnabzenecWindow", "Заявки"))
        self.buy_button.setText(_translate("SnabzenecWindow", "Закупки"))
        self.stock_label.setText(_translate("SnabzenecWindow", "Склад"))
        item = self.info_table.horizontalHeaderItem(0)
        item.setText(_translate("SnabzenecWindow", "ID материала"))
        item = self.info_table.horizontalHeaderItem(1)
        item.setText(_translate("SnabzenecWindow", "Цвет пластика"))
        item = self.info_table.horizontalHeaderItem(2)
        item.setText(_translate("SnabzenecWindow", "Толщина нити"))
        item = self.info_table.horizontalHeaderItem(3)
        item.setText(_translate("SnabzenecWindow", "Тип пластика"))
        item = self.info_table.horizontalHeaderItem(4)
        item.setText(_translate("SnabzenecWindow", "Количество"))
        self.application_label.setText(_translate("SnabzenecWindow", "Заявки"))
        item = self.application_info_table.horizontalHeaderItem(0)
        item.setText(_translate("SnabzenecWindow", "Номер заявки"))
        item = self.application_info_table.horizontalHeaderItem(1)
        item.setText(_translate("SnabzenecWindow", "Материал"))
        item = self.application_info_table.horizontalHeaderItem(2)
        item.setText(_translate("SnabzenecWindow", "Количество"))
        item = self.application_info_table.horizontalHeaderItem(3)
        item.setText(_translate("SnabzenecWindow", "Дата оформления"))
        item = self.application_info_table.horizontalHeaderItem(4)
        item.setText(_translate("SnabzenecWindow", "Дата поставки"))
        item = self.application_info_table.horizontalHeaderItem(5)
        item.setText(_translate("SnabzenecWindow", "Статус заявки"))
        self.send_material_button.setText(_translate("SnabzenecWindow", "Отправить\n"
            " материал"))
        self.date_button.setText(_translate("SnabzenecWindow", "Сообщить дату\n"
            " поставки"))

    def show_sklad(self):
        self.zakupka_group.hide()
        self.zayavka_frame.hide()
        self.sklad_group.show()

    def show_zayavka(self):
        self.sklad_group.hide()
        self.zakupka_group.hide()
        self.zayavka_frame.show()

    def show_zakupka(self):
        self.zayavka_frame.hide()
        self.sklad_group.hide()
        self.zakupka_group.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SnabzenecWindow = QtWidgets.QMainWindow()
    ui = UiSnabzenecWindow()
    ui.setupUi(SnabzenecWindow)
    SnabzenecWindow.show()
    sys.exit(app.exec_())

