# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Универ\Программная инженерия\Интерфейс\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from interface.orderinfowindow import OrderInfoWindow
from functools import partial

class UiMainWindow(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(851, 678)
        main_window.setMinimumHeight(687)
        main_window.setMinimumWidth(851)
        main_window.setMaximumHeight(687)
        main_window.setMaximumWidth(851)
        main_window.setStyleSheet("background-color: rgb(0, 51, 102);")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.manager_window = QtWidgets.QFrame(self.centralwidget)
        self.manager_window.setEnabled(True)
        self.manager_window.setGeometry(QtCore.QRect(-1, -1, 1231, 661))
        self.manager_window.setStyleSheet("")
        self.manager_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_window.setObjectName("manager_window")
        self.label_4 = QtWidgets.QLabel(self.manager_window)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.create_order_button = QtWidgets.QPushButton(self.manager_window)
        self.create_order_button.setEnabled(True)
        self.create_order_button.setGeometry(QtCore.QRect(20, 60, 170, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.create_order_button.setFont(font)
        self.create_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.create_order_button.setObjectName("create_order_button")
        self.refactor_order_button = QtWidgets.QPushButton(self.manager_window)
        self.refactor_order_button.setEnabled(True)
        self.refactor_order_button.setGeometry(QtCore.QRect(200, 60, 170, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refactor_order_button.setFont(font)
        self.refactor_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.refactor_order_button.setObjectName("refactor_order_button")
        self.show_orders_info_button = QtWidgets.QPushButton(self.manager_window)
        self.show_orders_info_button.setEnabled(True)
        self.show_orders_info_button.setGeometry(QtCore.QRect(380, 60, 341, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.show_orders_info_button.setFont(font)
        self.show_orders_info_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.show_orders_info_button.setObjectName("show_orders_info_button")
        self.manager_create_order_group = QtWidgets.QFrame(self.manager_window)
        self.manager_create_order_group.setEnabled(True)
        self.manager_create_order_group.setGeometry(QtCore.QRect(0, 129, 851, 531))
        self.manager_create_order_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_create_order_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_create_order_group.setObjectName("manager_create_order_group")
        self.label_7 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_7.setGeometry(QtCore.QRect(40, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_5.setGeometry(QtCore.QRect(300, 0, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_9.setGeometry(QtCore.QRect(40, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.surname_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.surname_text.setGeometry(QtCore.QRect(160, 98, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surname_text.setFont(font)
        self.surname_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.surname_text.setText("")
        self.surname_text.setObjectName("surname_text")
        self.name_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.name_text.setGeometry(QtCore.QRect(160, 138, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_text.setFont(font)
        self.name_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_text.setText("")
        self.name_text.setObjectName("name_text")
        self.patronimic_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.patronimic_text.setEnabled(True)
        self.patronimic_text.setGeometry(QtCore.QRect(160, 178, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patronimic_text.setFont(font)
        self.patronimic_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.patronimic_text.setText("")
        self.patronimic_text.setObjectName("patronimic_text")
        self.label_10 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_10.setGeometry(QtCore.QRect(40, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.phone_text = QtWidgets.QLineEdit(self.manager_create_order_group)
        self.phone_text.setEnabled(True)
        self.phone_text.setGeometry(QtCore.QRect(160, 218, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_text.setFont(font)
        self.phone_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone_text.setText("")
        self.phone_text.setObjectName("phone_text")
        self.label_11 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_11.setGeometry(QtCore.QRect(470, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.additional_info_text = QtWidgets.QTextEdit(self.manager_create_order_group)
        self.additional_info_text.setGeometry(QtCore.QRect(490, 90, 331, 91))
        self.additional_info_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.additional_info_text.setObjectName("additional_info_text")
        self.label_12 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_12.setGeometry(QtCore.QRect(20, 274, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.file_with_model_radio = QtWidgets.QRadioButton(self.manager_create_order_group)
        self.file_with_model_radio.setGeometry(QtCore.QRect(40, 314, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_with_model_radio.setFont(font)
        self.file_with_model_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_with_model_radio.setChecked(True)
        self.file_with_model_radio.setObjectName("file_with_model_radio")
        self.sketch_of_model_radio = QtWidgets.QRadioButton(self.manager_create_order_group)
        self.sketch_of_model_radio.setGeometry(QtCore.QRect(230, 314, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sketch_of_model_radio.setFont(font)
        self.sketch_of_model_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sketch_of_model_radio.setObjectName("sketch_of_model_radio")
        self.select_file_button = QtWidgets.QPushButton(self.manager_create_order_group)
        self.select_file_button.setEnabled(True)
        self.select_file_button.setGeometry(QtCore.QRect(230, 340, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.select_file_button.setFont(font)
        self.select_file_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.select_file_button.setObjectName("select_file_button")
        self.selected_fil_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.selected_fil_label.setGeometry(QtCore.QRect(80, 344, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selected_fil_label.setFont(font)
        self.selected_fil_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_fil_label.setObjectName("selected_fil_label")
        self.label_14 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_14.setGeometry(QtCore.QRect(20, 388, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_15.setGeometry(QtCore.QRect(40, 470, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_16.setGeometry(QtCore.QRect(40, 430, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.type_of_plastic_combobox = QtWidgets.QComboBox(self.manager_create_order_group)
        self.type_of_plastic_combobox.setGeometry(QtCore.QRect(200, 428, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.type_of_plastic_combobox.setFont(font)
        self.type_of_plastic_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.type_of_plastic_combobox.setObjectName("type_of_plastic_combobox")
        self.color_of_plastic_combobox = QtWidgets.QComboBox(self.manager_create_order_group)
        self.color_of_plastic_combobox.setGeometry(QtCore.QRect(200, 468, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.color_of_plastic_combobox.setFont(font)
        self.color_of_plastic_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color_of_plastic_combobox.setObjectName("color_of_plastic_combobox")
        self.label_17 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_17.setGeometry(QtCore.QRect(470, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.short_description_text = QtWidgets.QTextEdit(self.manager_create_order_group)
        self.short_description_text.setGeometry(QtCore.QRect(490, 250, 331, 91))
        self.short_description_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.short_description_text.setObjectName("short_description_text")
        self.label_18 = QtWidgets.QLabel(self.manager_create_order_group)
        self.label_18.setGeometry(QtCore.QRect(470, 370, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.finale_price_label = QtWidgets.QLabel(self.manager_create_order_group)
        self.finale_price_label.setGeometry(QtCore.QRect(490, 410, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.finale_price_label.setFont(font)
        self.finale_price_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.finale_price_label.setObjectName("finale_price_label")
        self.add_order_button = QtWidgets.QPushButton(self.manager_create_order_group)
        self.add_order_button.setEnabled(True)
        self.add_order_button.setGeometry(QtCore.QRect(630, 450, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_order_button.setFont(font)
        self.add_order_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.add_order_button.setObjectName("add_order_button")
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.surname_text.raise_()
        self.name_text.raise_()
        self.patronimic_text.raise_()
        self.label_10.raise_()
        self.phone_text.raise_()
        self.label_11.raise_()
        self.additional_info_text.raise_()
        self.label_12.raise_()
        self.file_with_model_radio.raise_()
        self.sketch_of_model_radio.raise_()
        self.select_file_button.raise_()
        self.selected_fil_label.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.type_of_plastic_combobox.raise_()
        self.color_of_plastic_combobox.raise_()
        self.label_17.raise_()
        self.short_description_text.raise_()
        self.label_18.raise_()
        self.finale_price_label.raise_()
        self.add_order_button.raise_()
        self.manager_refactore_order_group = QtWidgets.QFrame(self.manager_window)
        self.manager_refactore_order_group.setEnabled(True)
        self.manager_refactore_order_group.setGeometry(QtCore.QRect(0, 130, 1231, 531))
        self.manager_refactore_order_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_refactore_order_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_refactore_order_group.setObjectName("manager_refactore_order_group")
        self.manager_refactore_order_group.hide()
        self.label_19 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_19.setGeometry(QtCore.QRect(420, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_20.setGeometry(QtCore.QRect(400, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_21.setGeometry(QtCore.QRect(420, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_22.setGeometry(QtCore.QRect(460, 0, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_23.setGeometry(QtCore.QRect(420, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.surname_text_ref = QtWidgets.QLineEdit(self.manager_refactore_order_group)
        self.surname_text_ref.setGeometry(QtCore.QRect(540, 98, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surname_text_ref.setFont(font)
        self.surname_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.surname_text_ref.setText("")
        self.surname_text_ref.setObjectName("surname_text_ref")
        self.name_text_ref = QtWidgets.QLineEdit(self.manager_refactore_order_group)
        self.name_text_ref.setGeometry(QtCore.QRect(540, 138, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_text_ref.setFont(font)
        self.name_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_text_ref.setText("")
        self.name_text_ref.setObjectName("name_text_ref")
        self.patronimic_text_ref = QtWidgets.QLineEdit(self.manager_refactore_order_group)
        self.patronimic_text_ref.setEnabled(True)
        self.patronimic_text_ref.setGeometry(QtCore.QRect(540, 178, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patronimic_text_ref.setFont(font)
        self.patronimic_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.patronimic_text_ref.setText("")
        self.patronimic_text_ref.setObjectName("patronimic_text_ref")
        self.label_24 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_24.setGeometry(QtCore.QRect(420, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.phone_text_ref = QtWidgets.QLineEdit(self.manager_refactore_order_group)
        self.phone_text_ref.setEnabled(True)
        self.phone_text_ref.setGeometry(QtCore.QRect(540, 218, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_text_ref.setFont(font)
        self.phone_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone_text_ref.setText("")
        self.phone_text_ref.setObjectName("phone_text_ref")
        self.label_25 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_25.setGeometry(QtCore.QRect(850, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.additional_info_text_ref = QtWidgets.QTextEdit(self.manager_refactore_order_group)
        self.additional_info_text_ref.setGeometry(QtCore.QRect(870, 90, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.additional_info_text_ref.setFont(font)
        self.additional_info_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.additional_info_text_ref.setObjectName("additional_info_text_ref")
        self.label_26 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_26.setGeometry(QtCore.QRect(400, 274, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.file_with_model_radio_ref = QtWidgets.QRadioButton(self.manager_refactore_order_group)
        self.file_with_model_radio_ref.setGeometry(QtCore.QRect(420, 314, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_with_model_radio_ref.setFont(font)
        self.file_with_model_radio_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.file_with_model_radio_ref.setChecked(True)
        self.file_with_model_radio_ref.setObjectName("file_with_model_radio_ref")
        self.sketch_of_model_radio_ref = QtWidgets.QRadioButton(self.manager_refactore_order_group)
        self.sketch_of_model_radio_ref.setGeometry(QtCore.QRect(610, 314, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sketch_of_model_radio_ref.setFont(font)
        self.sketch_of_model_radio_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.sketch_of_model_radio_ref.setObjectName("sketch_of_model_radio_ref")
        self.select_file_button_ref = QtWidgets.QPushButton(self.manager_refactore_order_group)
        self.select_file_button_ref.setEnabled(True)
        self.select_file_button_ref.setGeometry(QtCore.QRect(610, 340, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.select_file_button_ref.setFont(font)
        self.select_file_button_ref.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.select_file_button_ref.setObjectName("select_file_button_ref")
        self.selected_fil_label_ref = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.selected_fil_label_ref.setGeometry(QtCore.QRect(460, 344, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selected_fil_label_ref.setFont(font)
        self.selected_fil_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_fil_label_ref.setObjectName("selected_fil_label_ref")
        self.label_28 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_28.setGeometry(QtCore.QRect(400, 388, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_29.setGeometry(QtCore.QRect(420, 470, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_30.setGeometry(QtCore.QRect(420, 430, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.type_of_plastic_combobox_ref = QtWidgets.QComboBox(self.manager_refactore_order_group)
        self.type_of_plastic_combobox_ref.setGeometry(QtCore.QRect(580, 428, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.type_of_plastic_combobox_ref.setFont(font)
        self.type_of_plastic_combobox_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.type_of_plastic_combobox_ref.setObjectName("type_of_plastic_combobox_ref")
        self.color_of_plastic_combobox_ref = QtWidgets.QComboBox(self.manager_refactore_order_group)
        self.color_of_plastic_combobox_ref.setGeometry(QtCore.QRect(580, 468, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.color_of_plastic_combobox_ref.setFont(font)
        self.color_of_plastic_combobox_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.color_of_plastic_combobox_ref.setObjectName("color_of_plastic_combobox_ref")
        self.label_31 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_31.setGeometry(QtCore.QRect(850, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.short_description_text_ref = QtWidgets.QTextEdit(self.manager_refactore_order_group)
        self.short_description_text_ref.setGeometry(QtCore.QRect(870, 260, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.short_description_text_ref.setFont(font)
        self.short_description_text_ref.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.short_description_text_ref.setObjectName("short_description_text_ref")
        self.label_32 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_32.setGeometry(QtCore.QRect(850, 370, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.finale_price_label_ref = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.finale_price_label_ref.setGeometry(QtCore.QRect(870, 410, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.finale_price_label_ref.setFont(font)
        self.finale_price_label_ref.setStyleSheet("color: rgb(255, 255, 255);")
        self.finale_price_label_ref.setObjectName("finale_price_label_ref")
        self.refactore_order_button_ref = QtWidgets.QPushButton(self.manager_refactore_order_group)
        self.refactore_order_button_ref.setEnabled(True)
        self.refactore_order_button_ref.setGeometry(QtCore.QRect(980, 450, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refactore_order_button_ref.setFont(font)
        self.refactore_order_button_ref.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.refactore_order_button_ref.setObjectName("refactore_order_button_ref")
        self.need_refactoring_order_combobox = QtWidgets.QComboBox(self.manager_refactore_order_group)
        self.need_refactoring_order_combobox.setGeometry(QtCore.QRect(40, 100, 301, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.need_refactoring_order_combobox.setFont(font)
        self.need_refactoring_order_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.need_refactoring_order_combobox.setObjectName("need_refactoring_order_combobox")
        self.label_27 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_27.setGeometry(QtCore.QRect(20, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.label_33 = QtWidgets.QLabel(self.manager_refactore_order_group)
        self.label_33.setGeometry(QtCore.QRect(20, 150, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.note_of_refactoring = QtWidgets.QTextEdit(self.manager_refactore_order_group)
        self.note_of_refactoring.setGeometry(QtCore.QRect(40, 190, 301, 301))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.note_of_refactoring.setFont(font)
        self.note_of_refactoring.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.note_of_refactoring.setObjectName("note_of_refactoring")
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.surname_text_ref.raise_()
        self.name_text_ref.raise_()
        self.patronimic_text_ref.raise_()
        self.label_24.raise_()
        self.phone_text_ref.raise_()
        self.label_25.raise_()
        self.additional_info_text_ref.raise_()
        self.label_26.raise_()
        self.file_with_model_radio_ref.raise_()
        self.sketch_of_model_radio_ref.raise_()
        self.select_file_button_ref.raise_()
        self.selected_fil_label_ref.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.type_of_plastic_combobox_ref.raise_()
        self.color_of_plastic_combobox_ref.raise_()
        self.label_31.raise_()
        self.short_description_text_ref.raise_()
        self.label_32.raise_()
        self.finale_price_label_ref.raise_()
        self.refactore_order_button_ref.raise_()
        self.need_refactoring_order_combobox.raise_()
        self.label_27.raise_()
        self.label_33.raise_()
        self.note_of_refactoring.raise_()
        self.manager_show_orders_info_group = QtWidgets.QFrame(self.manager_window)
        self.manager_show_orders_info_group.setGeometry(QtCore.QRect(0, 130, 741, 531))
        self.manager_show_orders_info_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manager_show_orders_info_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manager_show_orders_info_group.setObjectName("manager_show_orders_info_group")
        self.manager_show_orders_info_group.hide()
        self.orders_info_table = QtWidgets.QTableWidget(self.manager_show_orders_info_group)
        self.orders_info_table.setGeometry(QtCore.QRect(20, 60, 701, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.orders_info_table.setFont(font)
        self.orders_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.orders_info_table.setDragEnabled(False)
        self.orders_info_table.setAlternatingRowColors(False)
        self.orders_info_table.setShowGrid(True)
        self.orders_info_table.setRowCount(12)
        self.orders_info_table.setColumnCount(4)
        self.orders_info_table.setObjectName("orders_info_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(0, item)
        self.orders_info_table.setColumnWidth(0, 130)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(1, item)
        self.orders_info_table.setColumnWidth(1, 140)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(2, item)
        self.orders_info_table.setColumnWidth(2, 285)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.orders_info_table.setHorizontalHeaderItem(3, item)
        self.orders_info_table.setColumnWidth(3, 120)
        item = QtWidgets.QTableWidgetItem()
        self.orders_info_table.setItem(0, 0, item)
        self.label_64 = QtWidgets.QLabel(self.manager_show_orders_info_group)
        self.label_64.setGeometry(QtCore.QRect(210, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_64.setObjectName("label_64")
        self.show_more_info_button = QtWidgets.QPushButton(self.manager_show_orders_info_group)
        self.show_more_info_button.setEnabled(True)
        self.show_more_info_button.setGeometry(QtCore.QRect(250, 460, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.show_more_info_button.setFont(font)
        self.show_more_info_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(171,171,171,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.show_more_info_button.setObjectName("show_more_info_button")
        self.manager_window.raise_()
        self.additional_info_text_ref.raise_()
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.create_order_button.clicked.connect(self.showCreateOrder)
        self.refactor_order_button.clicked.connect(self.showRefactore)
        self.show_orders_info_button.clicked.connect(self.showOrdersInfo)

        self.order_info_window = OrderInfoWindow()

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.label_4.setText(_translate("main_window", "Менджер по работе с клиентами"))
        self.create_order_button.setText(_translate("main_window", "Офромить заказ"))
        self.refactor_order_button.setText(_translate("main_window", "Доработать заказ"))
        self.show_orders_info_button.setText(_translate("main_window", "Просмотреть информацию о заказах"))
        self.label_7.setText(_translate("main_window", "Фамилия"))
        self.label_6.setText(_translate("main_window", "Информация о клиенте"))
        self.label_8.setText(_translate("main_window", "Имя"))
        self.label_5.setText(_translate("main_window", "ОФОРМЛЕНИЕ ЗАКАЗА"))
        self.label_9.setText(_translate("main_window", "Отчество"))
        self.label_10.setText(_translate("main_window", "Телефон"))
        self.label_11.setText(_translate("main_window", "Дополнительная информация"))
        self.label_12.setText(_translate("main_window", "Информация о моделе"))
        self.file_with_model_radio.setText(_translate("main_window", "Файл с моделью"))
        self.sketch_of_model_radio.setText(_translate("main_window", "Эскиз модели"))
        self.select_file_button.setText(_translate("main_window", "Выбрать файл"))
        self.selected_fil_label.setText(_translate("main_window", "Файл не выбран"))
        self.label_14.setText(_translate("main_window", "Материалы модели"))
        self.label_15.setText(_translate("main_window", "Цвет пластика"))
        self.label_16.setText(_translate("main_window", "Тип пластика"))
        self.label_17.setText(_translate("main_window", "Краткое описание"))
        self.label_18.setText(_translate("main_window", "Итоговая сумма"))
        self.finale_price_label.setText(_translate("main_window", "0 рублей"))
        self.add_order_button.setText(_translate("main_window", "Добавить заказ"))
        self.label_19.setText(_translate("main_window", "Фамилия"))
        self.label_20.setText(_translate("main_window", "Информация о клиенте"))
        self.label_21.setText(_translate("main_window", "Имя"))
        self.label_22.setText(_translate("main_window", "ДОРАБОТАТЬ ЗАКАЗ"))
        self.label_23.setText(_translate("main_window", "Отчество"))
        self.label_24.setText(_translate("main_window", "Телефон"))
        self.label_25.setText(_translate("main_window", "Дополнительная информация"))
        self.additional_info_text_ref.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_26.setText(_translate("main_window", "Информация о моделе"))
        self.file_with_model_radio_ref.setText(_translate("main_window", "Файл с моделью"))
        self.sketch_of_model_radio_ref.setText(_translate("main_window", "Эскиз модели"))
        self.select_file_button_ref.setText(_translate("main_window", "Выбрать файл"))
        self.selected_fil_label_ref.setText(_translate("main_window", "Файл не выбран"))
        self.label_28.setText(_translate("main_window", "Материалы модели"))
        self.label_29.setText(_translate("main_window", "Цвет пластика"))
        self.label_30.setText(_translate("main_window", "Тип пластика"))
        self.label_31.setText(_translate("main_window", "Краткое описание"))
        self.short_description_text_ref.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_32.setText(_translate("main_window", "Итоговая сумма"))
        self.finale_price_label_ref.setText(_translate("main_window", "0 рублей"))
        self.refactore_order_button_ref.setText(_translate("main_window", "Обновить информацию"))
        self.label_27.setText(_translate("main_window", "Требующие доработки заказы"))
        self.label_33.setText(_translate("main_window", "Заметка об исправлении"))
        item = self.orders_info_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "Номер заказа"))
        item = self.orders_info_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Дата оформления"))
        item = self.orders_info_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Описание"))
        item = self.orders_info_table.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "Статус"))
        __sortingEnabled = self.orders_info_table.isSortingEnabled()
        self.orders_info_table.setSortingEnabled(False)
        self.orders_info_table.setSortingEnabled(__sortingEnabled)
        self.label_64.setText(_translate("main_window", "ИНФОРМАЦИЯ О ЗАКАЗАХ"))
        self.show_more_info_button.setText(_translate("main_window", "Подробная информация"))

    def showCreateOrder(self):
        self.manager_create_order_group.show()
        self.manager_refactore_order_group.hide()
        self.manager_show_orders_info_group.hide()
        main_window.resize(851, 678)
        main_window.setMinimumWidth(851)
        main_window.setMaximumWidth(851)

    def showRefactore(self):
        self.manager_refactore_order_group.show()
        self.manager_show_orders_info_group.hide()
        self.manager_create_order_group.hide()
        main_window.resize(1231, 678)
        main_window.setMinimumWidth(1231)
        main_window.setMaximumWidth(1231)

    def showOrdersInfo(self):
        self.manager_create_order_group.hide()
        self.manager_refactore_order_group.hide()
        self.manager_show_orders_info_group.show()
        main_window.resize(741, 678)
        main_window.setMinimumWidth(741)
        main_window.setMaximumWidth(741)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())

