# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Универ\Программная инженерия\Интерфейс\orderinfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_order_info(object):
    def setupUi(self, order_info):
        order_info.setObjectName("order_info")
        order_info.resize(401, 290)
        order_info.setMinimumHeight(290)
        order_info.setMinimumWidth(401)
        order_info.setMaximumHeight(290)
        order_info.setMaximumWidth(401)
        order_info.setStyleSheet("background-color: rgb(0, 51, 102);")
        self.order_info_table = QtWidgets.QTableWidget(order_info)
        self.order_info_table.setGeometry(QtCore.QRect(60, 60, 280, 152))
        self.order_info_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.order_info_table.setColumnCount(1)
        self.order_info_table.setObjectName("order_info_2")
        self.order_info_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        item.setFont(font)
        self.order_info_table.setItem(4, 0, item)
        self.order_info_table.horizontalHeader().setVisible(False)
        self.order_info_table.horizontalHeader().setDefaultSectionSize(172)
        self.cancel_button = QtWidgets.QPushButton(order_info)
        self.cancel_button.setEnabled(True)
        self.cancel_button.setGeometry(QtCore.QRect(130, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(125,125,125,1));\n"
"border-color: rgb(102, 102, 102);\n"
"border: 2px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"")
        self.cancel_button.setObjectName("cancel_button")
        self.label_4 = QtWidgets.QLabel(order_info)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(order_info)
        QtCore.QMetaObject.connectSlotsByName(order_info)

    def retranslateUi(self, order_info):
        _translate = QtCore.QCoreApplication.translate
        order_info.setWindowTitle(_translate("order_info", "Form"))
        item = self.order_info_table.verticalHeaderItem(0)
        item.setText(_translate("order_info", "Новая строка"))
        item = self.order_info_table.verticalHeaderItem(1)
        item.setText(_translate("order_info", "Фамилия"))
        item = self.order_info_table.verticalHeaderItem(2)
        item.setText(_translate("order_info", "Имя"))
        item = self.order_info_table.verticalHeaderItem(3)
        item.setText(_translate("order_info", "Отчество"))
        item = self.order_info_table.verticalHeaderItem(4)
        item.setText(_translate("order_info", "Материал"))
        __sortingEnabled = self.order_info_table.isSortingEnabled()
        self.order_info_table.setSortingEnabled(False)
        self.order_info_table.setSortingEnabled(__sortingEnabled)
        self.cancel_button.setText(_translate("order_info", "Закрыть"))
        self.label_4.setText(_translate("order_info", "Информация о заказе №"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    order_info = QtWidgets.QWidget()
    ui = Ui_order_info()
    ui.setupUi(order_info)
    order_info.show()
    sys.exit(app.exec_())

